services:
    phpbb.topicprefixes.listener:
        class: phpbb\topicprefixes\event\listener
        tags:
            - { name: event.listener }

    phpbb.topicprefixes.admin_controller:
        class: phpbb\topicprefixes\controller\admin_controller
        arguments:
            - '@phpbb.topicprefixes.manager'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
